### ISSUE TITLE
  Package devinweb/laravel-hyperpay has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

### ISSUE THREAD

**Issue by phaiderh** [devinweb/laravel-hyperpay#10]
Hello,

Thanks for this amazing package.

When I tried to install the package I got this error:

`Package devinweb/laravel-hyperpay has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  `

Ant tip?

**Comment by darbaoui** [comment]
@phaiderh what your php version?

**Comment by phaiderh** [comment]
@darbaoui  PHP 8.0.3

**Comment by phaiderh** [comment]
Is there any solution?

**Comment by darbaoui** [comment]
@phaiderh for sure, im working on it

**Comment by darbaoui** [comment]
issue fixed 1755daff4e212147d5f6442dacbf48cc2e4babcc
@phaiderh try to update `laravel-hyperpay` to the last version `1.0.1`

**Comment by phaiderh** [comment]
Thank, it's worked!
