### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by phaiderh** [devinweb/laravel-hyperpay#25]
Hello @darbaoui 

When I tried to prepare a checkout it's give an error:

Array to string conversion

Before two weeks maybe or less, I make it and every thing is working perfectly. So, I continue working on other tasks and features; but now I tried to test it and it not working because of that error ?!!

Can you help.?

Thanks.

**Comment by darbaoui** [comment]
@phaiderh couls you please share with me the error ?

**Comment by phaiderh** [comment]
@darbaoui Here you go

<img width="1328" alt="Screen Shot 2021-11-19 at 8 05 03 PM" src="https://user-images.githubusercontent.com/8259343/142662773-d4eeb22a-9f0f-4841-8d63-3f24c0c43cf5.png">

**Comment by phaiderh** [comment]
@darbaoui Hi, I found it, the error was with my prepareCheckout method.

Thanks & Sorry for inconvenience.
